<a href="https://colab.research.google.com/github/an0zie/NetworkAutomationPython/blob/main/DataScieneceLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TITLE

## SUBTITLE 1.1

In [ ]:
print("hello world")

hello world

In [ ]:
"hello world"

'hello world'

In [ ]:
#   printing my name
print("Michael")

Michael

In [ ]:
type("hello world ")

str

In [ ]:
"hello world".upper()

'HELLO WORLD'

In [ ]:
"hello world".lower()

'hello world'

In [ ]:
"hello world".capitalize()

'Hello world'

In [ ]:
"hello world".title()

'Hello World'

In [ ]:
# how many times l is in the string
"hello world".count('l')

3

In [ ]:
# replace a word in a string with another word
"hello world".replace('l','r')

'herro worrd'

# VARIABLE

In [ ]:
message_1 = "im learning python"
print(message_1)

im learning python

In [ ]:
message_2 = " and its fun "

In [ ]:
message_2

' and its fun '

In [ ]:
message = message_1 + message_2

In [ ]:
message

'im learning python and its fun '

In [ ]:
f'Hello world {message_1} and {message_2}'

'Hello world im learning python and  and its fun '

# 4 LIST

In [ ]:
# lists in python
countries =['United states', 'Germany', 'india','China']

In [ ]:
countries

['United states', 'Germany', 'india', 'China']

In [ ]:
# in a list you can combine integers (numbers) and strings
count = ['united',2 ,'color45','happy']

In [ ]:
count

['united', 2, 'color45', 'happy']

In [ ]:
# indexing
print(countries[0])
print(countries[1])
print(countries[2])
print(countries[3])

United states
Germany
india
China

In [ ]:
# negative indexing : starting from the last element  to the first element or what ever element you want to stop at in a list
print(countries[-1]) # the last element
print(countries[-2])
print(countries[-3])
print(countries[-4])

China
india
Germany
United states

In [ ]:
# slicing : accessing parts of a list, a slice  is a subset of list elements
countries[0:4] # list_name[start:stop]

['United states', 'Germany', 'india', 'China']

In [ ]:
countries [1:4]

['Germany', 'india', 'China']

In [ ]:
# another way of wrting a slice that you want to make sure it ends at the end of the list is  list_name[start:]


countries[1:]

['Germany', 'india', 'China']

In [ ]:
# another way of wrting a slice that you want to make sure it begins at the beginning of the list is  list_name[:stop]

countries[:4]

['United states', 'Germany', 'india', 'China']

# ADDING ELEMENTS TO A LIST

In [ ]:
countries

['United states', 'Germany', 'india', 'China']

In [ ]:
# used to add elemets to a list
countries.append('Aura salad')

In [ ]:
countries

['United states', 'Germany', 'india', 'China', 'Aura salad', 'Aura salad']

In [ ]:
# addding an element in a certain position
countries.insert(0,'Canada') # here we wanted it in position 0 index[0] which is the first position

In [ ]:
countries

['Canada',
 'Canada',
 'Canada',
 'Canada',
 'United states',
 'Germany',
 'india',
 'China',
 'Aura salad',
 'Aura salad']

In [ ]:
# we can join 2 list with the "+" sign like we did for strings
countriesss = countries + count

In [ ]:
countriesss

['Canada',
 'Canada',
 'Canada',
 'United states',
 'Germany',
 'india',
 'China',
 'Aura salad',
 'Aura salad',
 'united',
 2,
 'color45',
 'happy']

In [ ]:
countries.remove('Canada')

In [ ]:
countries

['Canada',
 'Canada',
 'Canada',
 'United states',
 'Germany',
 'india',
 'China',
 'Aura salad',
 'Aura salad']

In [ ]:
# so here you add 2 or more list  but there are "[]" to show which lists you added
nested_list=[countries, count]

In [ ]:
nested_list

[['Canada',
  'Canada',
  'Canada',
  'United states',
  'Germany',
  'india',
  'China',
  'Aura salad',
  'Aura salad'],
 ['united', 2, 'color45', 'happy']]

In [ ]:
# removing a element from a list
countries.remove('Canada')

In [ ]:
countries

['Canada',
 'United states',
 'Germany',
 'india',
 'China',
 'Aura salad',
 'Aura salad']

In [ ]:
# you can also  remove an element by its index
countries.pop(-1) # the "-1" is the index of the element which in this case is the last element in a list

'Aura salad'

In [ ]:
countries

['Canada', 'United states', 'Germany', 'india', 'China', 'Aura salad']

In [ ]:
# you can also use "del " to remove a specific element with its indexbut unlike the ".pop" it doesnt show what element is being removed
del countries[0]

In [ ]:
countries

['United states', 'Germany', 'india', 'China', 'Aura salad']

# SORTING A LIST

In [ ]:
numbers = [1,3,5,6,8,7,9,4,2]

In [ ]:
# used to  sort numbers from smallest to the largest
numbers.sort()

In [ ]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# here we want to sort the elements of a string in descending order
numbers = [1,3,5,6,8,7,9,4,2]
numbers.sort(reverse=True)# this is to sort it in descending order (largest to smallest)

In [ ]:
numbers

[9, 8, 7, 6, 5, 4, 3, 2, 1]

# updating an element

In [ ]:
# this is used to update the value of an element in a string to a  new  element
numbers[0]=1000

In [ ]:
numbers

[1000, 8, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
numbers[-1]=30

In [ ]:
numbers

[1000, 8, 7, 6, 5, 4, 3, 2, 30]

# copying a list

In [ ]:
countries[:]# this means we want the whole list

['United states', 'Germany', 'india', 'China', 'Aura salad']

In [ ]:
new_list =countries[:]

In [ ]:
new_list

['United states', 'Germany', 'india', 'China', 'Aura salad']

In [ ]:
new_list_2= countries.copy() # used to make a copy of a list so you can use for other purposes

In [ ]:
new_list_2

['United states', 'Germany', 'india', 'China', 'Aura salad']

# DICTIONARY

In [ ]:
# A DICTIONARY IS AN ORDERED COLLECTION OF ITEMS USED TO STORE DATA VALUES AND IT CONTAINS A KEY AND VALUE
my_dict={'key1':'value1','key2':'value2'}

In [ ]:
my_data={'name':'Michael','Age':22} # you can mix different data types in a dictionary as you can see in our example

In [ ]:
my_data

{'name': 'Michael', 'Age': 22}

In [ ]:
my_data.keys()# used to get the keys of the dictionary

dict_keys(['name', 'Age'])

In [ ]:
my_data.values() #used to get the values of the dictionary

dict_values(['Michael', 22])

In [ ]:
my_data.items() # used to show the items (the ordered data stored in a dictionary)

dict_items([('name', 'Michael'), ('Age', 22)])

In [ ]:
my_data['height']=1.7 # used to add a new item to the dictionary

In [ ]:
my_data.items()

dict_items([('name', 'Michael'), ('Age', 22), ('height', 1.7)])

In [ ]:
my_data.update({'height': 1.8}) # used to update the value of a key in a dictionary

In [ ]:
my_data.items()

dict_items([('name', 'Michael'), ('Age', 22), ('height', 1.8)])

# COPY A DICTIONARY

In [ ]:
new_dict = my_data.copy()

In [ ]:
new_dict

{'name': 'Michael', 'Age': 22, 'height': 1.8}

# removing an element in a dictionary

In [ ]:
my_data.pop('name')

'Michael'

In [ ]:
my_data

{'Age': 22, 'height': 1.8}

In [ ]:
del my_data['Age']# another  of removing elemts from a dictionary

In [ ]:
my_data

{'height': 1.8}

In [ ]:
my_data.clear() # this is used to clear all elements from the dictionary

In [ ]:
my_data

{}

# IF STATEMENTS

In [ ]:
# executes a block of code if the conditions are met
#if <condition>:
#    <code>
#elif <condition>:
#    <code>
#else :
#    <code>

In [ ]:
age = 15

if age >= 18 :
    print('youre an adult')
elif age>=14 and age<=17: # "and "here is a logical operator
    print('youre a teen')
else:
    print('youre a child')

youre a teen

# FOR LOOP

In [ ]:
# here it does an iteration specific number of times
#for <variable > in <list>:
 #   <code>

In [ ]:
countries

['United states', 'Germany', 'india', 'China', 'Aura salad']

In [ ]:
for country in countries :
    print(country)

United states
Germany
india
China
Aura salad

In [ ]:
# enumerate : it is used with a for loop and returns the number of the loop
for i,country in enumerate (countries) :
    print(i)
    print(country)

0
United states
1
Germany
2
india
3
China
4
Aura salad

In [ ]:
my_dataa={'name':'Michael','Age':22}

In [ ]:
my_dataa

{'name': 'Michael', 'Age': 22}

In [ ]:
# looping through a dictionary
for key, value in my_dataa.items():
    print(key)
    print(value)

name
Michael
Age
22

# FUNCTION

In [ ]:
# a function is a block of code that only runs when it is called
# def function(<parmas>):
 #   <code>
 #   return <data>

In [ ]:
def sum_values(a,b):
    x = a+b
    return x

In [ ]:
sum_values(1,3)

4

# BUILT-IN FUNCTIONS

In [ ]:
countries

['United states', 'Germany', 'india', 'China', 'Aura salad']

In [ ]:
len(countries) # a built in function used to calculate the length of an iterable object(list)

5

In [ ]:
numbersss = [1,4,6,99,34,37]

In [ ]:
max(numbersss) # built in function used to calculate the max of values (integers mostly )

99

In [ ]:
min(numbersss)# built in function used to calculate the min of values (integers mostly )

1

In [ ]:
type (numbersss) # gives the type of an object like here numbersss is a list

list

In [ ]:
for i in range(1,10,2):
    print (i)

1
3
5
7
9

# MODULE

In [ ]:
import

# OS MODULE

In [ ]:
import os

In [ ]:
os.getcwd()# we get the directory our jupyter notebook file is located ,the"cwd" means current working directory

'C:\\Users\\DELL'

In [ ]:
os.listdir() # list all the elements in the folder (in this case DELL ) WHERE THIS JUPYTER FILE IS LOCATED

['.anaconda',
 '.android',
 '.antigravity',
 '.bash_history',
 '.claude',
 '.claude.json',
 '.conda',
 '.continuum',
 '.copilot',
 '.cursor',
 '.docker',
 '.emulator_console_auth_token',
 '.gemini',
 '.gitconfig',
 '.gradle',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.jupyter',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.node_repl_history',
 '.packettracer',
 '.python_history',
 '.VirtualBox',
 '.virtual_documents',
 '.vscode',
 'anaconda3',
 'anaconda_projects',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'blockchain_iot_integrity',
 'Cisco Packet Tracer 8.2.2',
 'Contacts',
 'Cookies',
 'DATASCIENECELEARNING',
 'DataScieneceLearning.ipynb',
 'db_backup',
 'db_backup_script',
 'Documents',
 'Downloads',
 'Favorites',
 'GNS3',
 'IdeaProjects',
 'IdeaSnapshots',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'maxima',
 'Music',
 'My Documents',
 'NetHood',
 'network-automation',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{ec574132-5b35-11f0-a80c-00dbdf98bade}.TM.blf',
 'NTUSER.DAT{ec574132-5b35-11f0-a80c-00dbdf98bade}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{ec574132-5b35-11f0-a80c-00dbdf98bade}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'PyCharmMiscProject',
 'PycharmProjects',
 'python_learning',
 'Recent',
 'Saved Games',
 'ScStore',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'titanic-project',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Videos',
 'VirtualBox VMs']

In [ ]:
os.makedirs("moree_learning") # makes a new folder

In [ ]:
os.listdir()

['.anaconda',
 '.android',
 '.antigravity',
 '.bash_history',
 '.claude',
 '.claude.json',
 '.conda',
 '.continuum',
 '.copilot',
 '.cursor',
 '.docker',
 '.emulator_console_auth_token',
 '.gemini',
 '.gitconfig',
 '.gradle',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.jupyter',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.node_repl_history',
 '.packettracer',
 '.python_history',
 '.VirtualBox',
 '.virtual_documents',
 '.vscode',
 'anaconda3',
 'anaconda_projects',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'blockchain_iot_integrity',
 'Cisco Packet Tracer 8.2.2',
 'Contacts',
 'Cookies',
 'DATASCIENECELEARNING',
 'DataScieneceLearning.ipynb',
 'db_backup',
 'db_backup_script',
 'Documents',
 'Downloads',
 'Favorites',
 'GNS3',
 'IdeaProjects',
 'IdeaSnapshots',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'maxima',
 'more_learning',
 'Music',
 'My Documents',
 'NetHood',
 'network-automation',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{ec574132-5b35-11f0-a80c-00dbdf98bade}.TM.blf',
 'NTUSER.DAT{ec574132-5b35-11f0-a80c-00dbdf98bade}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{ec574132-5b35-11f0-a80c-00dbdf98bade}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'PyCharmMiscProject',
 'PycharmProjects',
 'python_learning',
 'Recent',
 'Saved Games',
 'ScStore',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'titanic-project',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Videos',
 'VirtualBox VMs']

# INTRODUCTION TO PANDAS AND NUMPY

## PANDA

THIS ALLOWS TO CLEAN DATA , WRANGLE DATA , MAKE VISUALISATIONS AND MORE, THINK OF IT AS A " SUPER CHARGED MICROSOFT EXCEL "

BENEFITS OF PANDAS VS EXCEL
1. LIMITED BY SIZE : EXCEL CANT HANDLE 1 MILLION ROWS BUT PYTHON CAN HANDLE MILLIONS OF ROWS
2. COMPLEX DATA TRANSFORMATION : PYTON CAN HANDLE COMPLEX COMPUTATION
3. AUTOMATION
4. CROSS PLATFORM CAPABILITIES : PYTHON REMAINS THE REGARDLESS OF ANY SYSTEM YOU CHNAGE TO


ARRAYS: 1-DIMENSIONAL ARRAY (SERIES) AND 2-DIMENSIONAL ARRAY (DATAFRAME)
AND THEY ARE THE 2 IMPORTNAT STRUCTURES IN PANDAS AND IN PANDAS  WE MAINLY USE MORE OF DATAFRAME AS A PANDAS DATAFRAME IS EQUIVALENT TO AN EXCEL SPREADSHEET( WITH ROWS AND COLUMN(ALSO KNOWN AS SERIES IN PANDA DATAFRAME)

THE COLUMN NAME IS CALLED FEATURES
AND THE ROW NAME IS CALLED OBSERVATION

-- PANDAS TERMINOLOGY
   EXCEL    |         PANDAS
1. worksheet |      Dataframe
2. column     |      series
3. row heading |    index
4.  row        |      row
5.  Empty cell  |     NaN

WE CREATE A DATAFRAME WITH ARRAYS
TO USE ARRAYS WE USE A LIBRARY CALLED "NUM.py" AND Num.py is what is  under the hood of PANDAS

EXAMPLE OF NUM.py ARRAY
NUM.py Array
np.array([[1,4],[2,5],[3,6]])

## How to create a dataframe

firstly  we must always import both pandas and numpy

In [ ]:
import pandas as pd
import numpy as np

## Option1

In [ ]:
# creating an array
data = np.array([[1,3],[2,5],[6,7]])

In [ ]:
# creating a dataframe
df = pd.DataFrame(data,index=['row1','row2','row3'],columns=['col1','col2'] )

In [ ]:
# showing the dataframe
df

      col1  col2
row1     1     3
row2     2     5
row3     6     7

# OPTION 2

In [ ]:
#creating an array with list shape
data = [1,3],[2,5],[6,7]

In [ ]:
#creating a dataframe
dff = pd.DataFrame(data,index=['row1','row2','row3'],columns=['col1','col2'] )

In [ ]:
#showing the dataframe
dff

      col1  col2
row1     1     3
row2     2     5
row3     6     7

#  2 CREATING A DATAFRAME FROM A DICTIONARY

In [ ]:
# lists used for this example
state =['california','texas','florida','new york']
population=[100000,200000,300000,400000]

In [ ]:
# storing lists within a dictionary
my_states={'States': state , 'Population':population}

In [ ]:
# creating the dataframe
dwr = pd.DataFrame(my_states,index=['state1','state2','state3','state4'],columns=['States','Population'] )

In [ ]:
# showing the dataframe
dwr

            States  Population
state1  california      100000
state2       texas      200000
state3     florida      300000
state4    new york      400000

# 3 CREATING A DATAFRAME FROM CSV FILE

In [ ]:
# READING THE CSV FILE
webs=pd.read_csv('C:/Users/DELL/Downloads/student_performance_data.csv')

In [ ]:
webs

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.6720,C
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.0930,C
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.0355,B
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.5400,B
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.1005,B

In [ ]:
# SHOW FIRST 5 ROWS IN  A DATAFRAMES
webs.head() # the ".head()" shows the first 5 rows of the dataframe

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C

In [ ]:
# show last 5 rows in a dataframe
webs.tail()

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.6720,C
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.0930,C
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.0355,B
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.5400,B
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.1005,B

In [ ]:
# show first n rows in a dataframe
webs.head(10)# here i want to see the first 10 rows

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C
5,100005,Female,1.79,53.16,33.61,54.26,79.79,58.23,No,No,Bachelor,5.43,59.3525,C
6,100006,Male,7.99,55.47,45.49,87.83,67.37,53.07,No,Yes,High School,5.68,65.4890,C
7,100007,Male,8.63,73.92,47.14,95.69,85.06,79.55,Yes,No,Master,6.35,78.4685,B
8,100008,Male,2.64,70.24,53.65,56.28,40.72,76.70,No,No,Bachelor,5.12,53.7460,D
9,100009,Female,4.87,52.19,33.05,59.54,74.67,73.38,Yes,No,Bachelor,6.33,60.1865,C

In [ ]:
# show last n rows in a dataframe
webs.tail(10)# here i want to see the last 10 rows

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
9990,109990,Female,9.45,72.21,43.71,56.67,60.99,51.35,No,Yes,High School,4.32,56.6120,C
9991,109991,Female,6.22,52.90,83.75,99.38,96.81,98.12,Yes,Yes,High School,7.83,90.5805,A
9992,109992,Female,3.14,94.95,52.03,97.33,72.89,67.64,Yes,No,Bachelor,5.53,76.5090,B
9993,109993,Female,4.59,51.37,53.99,34.53,64.84,35.51,No,No,Master,5.15,50.8125,D
9994,109994,Female,7.82,42.91,47.65,93.15,55.22,95.24,No,Yes,Master,7.39,65.9595,C
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.6720,C
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.0930,C
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.0355,B
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.5400,B
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.1005,B

In [ ]:
# getting access to the shape attribute
# displays the all rows of the dataframe
webs.shape # shows the number of rows and columns

(10000, 14)

In [ ]:
#display n rows
pd.set_option('display.max_rows',1000)
webs

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.6720,C
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.0930,C
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.0355,B
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.5400,B
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.1005,B

# attributes

these are values associaated with an object (referenced by name using dotted expressions) df.column  "column "is the attribute of object "df"(dataframe name  in this case )

In [ ]:
# getting access to the shape attribute
webs.shape

(10000, 14)

In [ ]:
# getting access to the index attribute
webs.index # the rows of the dataframe

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
#getting access to the column attribute
webs.columns # the columns of the dataframe

Index(['student_id', 'gender', 'study_hours_per_day', 'attendance_percentage',
       'assignment_score', 'midterm_score', 'final_exam_score',
       'participation_score', 'internet_access', 'extra_classes',
       'parent_education', 'sleep_hours', 'overall_score', 'grade'],
      dtype='object')

In [ ]:
#data types of each column
webs.dtypes

student_id                 int64
gender                    object
study_hours_per_day      float64
attendance_percentage    float64
assignment_score         float64
midterm_score            float64
final_exam_score         float64
participation_score      float64
internet_access           object
extra_classes             object
parent_education          object
sleep_hours              float64
overall_score            float64
grade                     object
dtype: object

# METHODS
a function which is defined inside a class body
example
df.head() df is the dataframe name in this case as webs is the dataframe name in your own

In [ ]:
# showing the first 5 columns
webs.head()

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C

In [ ]:
# showing the info of the dataframe
webs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             10000 non-null  int64
 1   gender                 10000 non-null  object
 2   study_hours_per_day    10000 non-null  float64
 3   attendance_percentage  10000 non-null  float64
 4   assignment_score       10000 non-null  float64
 5   midterm_score          10000 non-null  float64
 6   final_exam_score       10000 non-null  float64
 7   participation_score    10000 non-null  float64
 8   internet_access        10000 non-null  object
 9   extra_classes          10000 non-null  object
 10  parent_education       10000 non-null  object
 11  sleep_hours            10000 non-null  float64
 12  overall_score          10000 non-null  float64
 13  grade                  10000 non-null  object
dtypes: float64(8), int64(1), object(5)
memory usage: 1.1+ MB

In [ ]:
# describing basic statistics of the dataframe
webs.describe()

,student_id,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,sleep_hours,overall_score
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,104999.50000,5.467825,70.493817,64.717809,62.322568,64.979987,55.103202,6.505165,63.826901
std,2886.89568,2.594134,17.295607,20.052779,21.710555,20.216141,25.955949,1.458246,10.230977
min,100000.00000,1.000000,40.000000,30.000000,25.000000,30.010000,10.000000,4.000000,33.263500
25%,102499.75000,3.220000,55.640000,47.320000,43.515000,47.400000,32.955000,5.220000,56.528125
50%,104999.50000,5.420000,70.780000,64.770000,62.050000,65.210000,55.055000,6.520000,63.780750
75%,107499.25000,7.740000,85.200000,81.760000,81.227500,82.500000,77.760000,7.792500,71.163125
max,109999.00000,10.000000,100.000000,99.990000,100.000000,100.000000,99.990000,9.000000,96.879500

# function
A group of related statements that perform a soecific task
example
min(),max() (python bult-in function)

In [ ]:
#obtaining the length of the dataframe(number of column)
len(webs)

10000

In [ ]:
#obtaining the highest index of the dataframe(number of column)
max(webs.index)

9999

In [ ]:
#obtaining the lowest indexof the dataframe(number of column)
min(webs.index)

0

In [ ]:
#obtaining the datatype
type(webs)

pandas.core.frame.DataFrame

In [ ]:
# rounding the value of the dataset
round(webs,2)

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.35,D
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.95,D
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.04,B
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.41,C
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.60,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.67,C
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.09,C
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.04,B
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.54,B
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.10,B

# SELECTING ONE COLUMN

## SYNTAX 1

In [ ]:
# select a column with [] (preferred way to select a column)
webs['gender']

0         Male
1       Female
2         Male
3         Male
4         Male
         ...
9995    Female
9996      Male
9997    Female
9998    Female
9999      Male
Name: gender, Length: 10000, dtype: object

In [ ]:
# check out the data type of a column
type(webs['gender'])

pandas.core.series.Series

In [ ]:
# series : attribute  and methods
webs['gender'].index
webs['gender'].head()

0      Male
1    Female
2      Male
3      Male
4      Male
Name: gender, dtype: object

## SYNTAX 2

In [ ]:
#select a column with .
webs.gender

0         Male
1       Female
2         Male
3         Male
4         Male
         ...
9995    Female
9996      Male
9997    Female
9998    Female
9999      Male
Name: gender, Length: 10000, dtype: object

# selecting 2 or more columns

In [ ]:
# selecting 2 columns using[[]]
webs[['gender', 'assignment_score']]

      gender  assignment_score
0       Male             36.47
1     Female             34.25
2       Male             72.29
3       Male             97.63
4       Male             65.19
...      ...               ...
9995  Female             60.41
9996    Male             62.45
9997  Female             67.08
9998  Female             97.73
9999    Male             93.33

[10000 rows x 2 columns]

In [ ]:
# check out the data type of the selection
type(webs[['gender', 'assignment_score']])

pandas.core.frame.DataFrame

In [ ]:
# select 2 or more column using [[]]
webs[['gender', 'assignment_score','attendance_percentage']]

      gender  assignment_score  attendance_percentage
0       Male             36.47                  69.98
1     Female             34.25                  84.80
2       Male             72.29                  73.76
3       Male             97.63                  45.00
4       Male             65.19                  51.13
...      ...               ...                    ...
9995  Female             60.41                  59.65
9996    Male             62.45                  83.62
9997  Female             67.08                  95.40
9998  Female             97.73                  78.24
9999    Male             93.33                  97.11

[10000 rows x 3 columns]

In [ ]:
# we cant select 2 or more columns with the "."
#webs.'gender', 'assignment_score' # the . sign reallys does work as well as the [[]]

# ADDING A COLUMN

## adding a new column with a scalar value

In [ ]:
# adding a new column to dataframe
webs['attenton_span_in_class']=70

In [ ]:
webs

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade,attenton_span_in_class
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D,70
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D,70
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B,70
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C,70
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.6720,C,70
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.0930,C,70
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.0355,B,70
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.5400,B,70
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.1005,B,70

## ADDING A NEW COLUMN WITH AN ARRAY
THE DATAFRAME HAS 10000 ROWS SO WE NEED TO CREATE AN ARRAY WITH 10000 ELEMENTS

In [ ]:
# IMPORT NUMPY
import numpy as np

In [ ]:
# CREATE AN ARRAY OF 10000 ELEMENTS
language = np.arange(0,10000)

In [ ]:
#length of array
len(language)

10000

In [ ]:
# adding a new column to dataframe with an array
webs['language']=language

In [ ]:
webs

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade,attenton_span_in_class,language
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D,70,0
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D,70,1
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B,70,2
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C,70,3
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C,70,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.6720,C,70,9995
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.0930,C,70,9996
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.0355,B,70,9997
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.5400,B,70,9998
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.1005,B,70,9999

In [ ]:
#create random integer numbers between1 and 100
nt_lang=np.random.randint(1,100,size=10000)

In [ ]:
#min value inclusive and high value exclusive
min(nt_lang)
max(nt_lang)

np.int32(99)

In [ ]:
#adding a new column to dataframe with an array
webs['language']=nt_lang

In [ ]:
webs

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade,attenton_span_in_class,language
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D,70,99
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D,70,63
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B,70,99
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C,70,86
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C,70,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.6720,C,70,68
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.0930,C,70,16
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.0355,B,70,53
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.5400,B,70,79
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.1005,B,70,35

In [ ]:
#adding a new column to dataframe with an array
webs['attenton_span_in_class']=nt_lang

In [ ]:
webs

,student_id,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,overall_score,grade,attenton_span_in_class,language
0,100000,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,52.3480,D,99,99
1,100001,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,53.9485,D,63,63
2,100002,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,82.0375,B,99,99
3,100003,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,66.4110,C,86,86
4,100004,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,65.6005,C,48,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,55.6720,C,68,68
9996,109996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,66.0930,C,16,16
9997,109997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,73.0355,B,53,53
9998,109998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,71.5400,B,79,79
9999,109999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,84.1005,B,35,35

In [ ]:
# create random float number between 1 and 100
np.random.uniform(1,100,size=10000)

array([82.99965376,  1.79799306, 61.44535429, ..., 24.14626572,
       65.54509347, 19.74002705], shape=(10000,))